apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/node-feature-discovery
- ../../bundles/patch-operator
- ../../bundles/clusterissuer-http01
- ../../base/rbac.authorization.k8s.io/clusterroles/allow-edit-rbac
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/kruize-admins
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-ops-manage-olm
- ../../base/core/namespaces/openshift-gitops
- externalsecrets
- issuers
- feature/odf
- certificates
- nodenetworkconfigurationpolicies
- secretstores

components:
  - ../../components/nerc-oauth-github

  # this must come last in order to apply
  # to all resources.
  - ../../components/argocd-skip-dryrun

generatorOptions:
  disableNameSuffixHash: true

patches:

- patch: |
    apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - name: github
        github:
          clientID: Ov23liGZVyeMB2D96Wiq
          teams:
            - ocp-on-nerc/nerc-ops
            - ocp-on-nerc/kruize-admins
- target:
    kind: ExternalSecret
    name: github-client-secret
  patch: |
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: nerc/nerc-ocp-test-2/openshift-config/github-client-secret

- target:
    kind: SecretStore
  patch: |
    - op: replace
      path: /spec/provider/vault/auth/kubernetes/mountPath
      value: kubernetes/nerc-ocp-test-2
- target:
    kind: ExternalSecret
    name: aws-route53-credentials
  patch: |
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: nerc/nerc-ocp-test-2/aws-route53-credentials
- target:
    kind: APIServer
    name: cluster
  patch: |
    - op: replace
      path: /spec/servingCerts/namedCertificates/0/names/0
      value: api.nerc-ocp-test-2.nerc.mghpcc.org
