---
# Source: zookeeper-operator/templates/post-install-upgrade-hooks.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-operator-post-install-upgrade
  namespace: default
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
data:
  validations.sh: |
    #!/bin/sh
    set -e
    sleep 30

    if [ -z "$(kubectl api-resources | grep ZookeeperCluster)" ]; then
        exit 1
    fi
---
# Source: zookeeper-operator/templates/pre-delete-hooks.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-operator-pre-delete
  namespace: default
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
data:
  pre-delete.sh: |
    #!/bin/sh
    exit_code=0
    echo "Checking for ZookeeperCluster Resource"

    ret=$(kubectl get zookeepercluster --all-namespaces --no-headers 2>&1)
    if (echo $ret | grep -e "No resources found" -e "the server doesn't have a resource type \"zookeepercluster\"" > /dev/null);
    then
      echo "None"
    else
      echo "$ret"
      exit_code=1
    fi

    if [ $exit_code -ne 0 ];
    then
      echo "Pre-delete Check Failed"
      exit $exit_code
    fi
    echo "Pre-delete Check OK"
