apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zookeeper
resources:
- serviceaccounts.yaml
- configmaps.yaml
- jobs.yaml
- rolebindings.yaml
- deployments.yaml
- zookeeperclusters.yaml
- networkpolicies.yaml
