apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: allow-list-crds

resources:
  - ../../base/rbac.authorization.k8s.io/clusterroles/allow-list-crds
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/allow-list-crds
