apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/acct-mgt
- ../../bundles/patch-operator
- ../../bundles/xdmod-reader
- ../../bundles/solr-helm-repo
- ../../bundles/ansible-automation-platform-operator
- ../../bundles/openshift-serverless-operator
- ../../bundles/amq-broker-rhel8-operator
- ../../bundles/crunchy-postgres-operator
- ../../bundles/amq-streams-operator
- ../../bundles/openshift-pipelines-operator
- ../../bundles/openshift-opentelemetry-operator
- ../../bundles/rhods-operator
- ../../bundles/node-feature-discovery
- ../../bundles/nvidia-gpu-operator
- ../../bundles/openshift-custom-metrics-autoscaler-operator
- ../../base/rbac.authorization.k8s.io/clusterroles/allow-edit-rbac
- feature/odf
- feature/custom-routes
- ../../base/core/namespaces/openshift-gitops
- externalsecrets
- secretstores
- issuers
- machineconfigs/disable-net-ifnames
- machineconfigs/udev-rules
- machineconfigs/configure-bond0
- nodenetworkconfigurationpolicies
- clusterversion.yaml
- certificates
- consolelinks
- odhdashboardconfigs

components:
  - ../../components/nerc-oauth-keycloak
  - ../../components/nerc-oauth-github

  # this must come last in order to apply
  # to all resources.
  - ../../components/argocd-skip-dryrun

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: admin-acks
  namespace: openshift-config
  behavior: merge
  literals:
    - ack-4.11-kube-1.25-api-removals-in-4.12=true
    - ack-4.12-kube-1.26-api-removals-in-4.13=true
- files:
  - config.yaml=configmaps/cluster-monitoring-config.yaml
  name: cluster-monitoring-config
  namespace: openshift-monitoring

patches:
- path: kubeletconfigs/system-reserved-patch.yaml
- target:
    kind: SecretStore
  patch: |
    - op: replace
      path: /spec/provider/vault/auth/kubernetes/mountPath
      value: kubernetes/nerc-ocp-prod
- patch: |
    apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - name: mss-keycloak
        openID:
          clientID: ocp-prod
- patch: |
    apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - name: github
        github:
          clientID: 771ea98004d436c6e529
- target:
    kind: ExternalSecret
    name: oauths-clientsecret-nerc
  patch: |
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: nerc/nerc-ocp-prod/openshift-config/oauths-clientsecret-nerc
- target:
    kind: ExternalSecret
    name: aws-route53-credentials
  patch: |
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: nerc/nerc-ocp-prod/aws-route53-credentials
- target:
    kind: ExternalSecret
    name: github-client-secret
  patch: |
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: nerc/nerc-ocp-prod/openshift-config/github-client-secret
- target:
    kind: APIServer
    name: cluster
  patch: |
    - op: replace
      path: /spec/servingCerts/namedCertificates/0/names/0
      value: api.shift.nerc.mghpcc.org
