apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/acct-mgt
- ../../bundles/patch-operator
- ../../bundles/moc-metrics-collector
- ../../bundles/solr-helm-repo
- ../../bundles/ansible-automation-platform-operator
- ../../bundles/openshift-serverless-operator
- ../../bundles/authorino-operator
- ../../bundles/servicemesh-operator
- ../../bundles/amq-broker-rhel8-operator
- ../../bundles/crunchy-postgres-operator
- ../../bundles/amq-streams-operator
- ../../bundles/openshift-pipelines-operator
- ../../bundles/openshift-opentelemetry-operator
- ../../bundles/rhods-operator
- ../../bundles/node-feature-discovery
- ../../bundles/nvidia-gpu-operator
- ../../bundles/openshift-custom-metrics-autoscaler-operator
- ../../bundles/clusterissuer-http01
- ../../bundles/curator
- ../../bundles/koku-metrics-operator
- ../../bundles/autopilot
- ../../bundles/mongodb-operator
- ../../bundles/elasticsearch-eck-operator
- ../../bundles/nagios-monitoring
- ../../bundles/allow-list-crds
- ../../base/rbac.authorization.k8s.io/clusterroles/allow-edit-rbac
- ../../base/rbac.authorization.k8s.io/clusterroles/application-edit
- ../../base/rbac.authorization.k8s.io/clusterroles/project-monitoring-edit
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-allow-sys-admin
- ../../base/security.openshift.io/securitycontextconstraints/nerc-allow-sys-admin
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-node-reader
- feature/odf
- feature/custom-routes
- ../../base/core/namespaces/openshift-gitops
- externalsecrets
- secretstores
- issuers
- machineconfigs/disable-net-ifnames
- machineconfigs/udev-rules
- machineconfigs/configure-bond0
- nodenetworkconfigurationpolicies
- clusterversion.yaml
- certificates
- consolelinks
- rhoai
- object-storage
- rolebindings
- groups

components:
  - ../../components/nerc-oauth-keycloak
  - ../../components/nerc-oauth-github
  - ../../components/resourcequotas/ope-course-quota

  # this must come last in order to apply
  # to all resources.
  - ../../components/argocd-skip-dryrun

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: admin-acks
  namespace: openshift-config
  behavior: merge
  literals:
    - ack-4.11-kube-1.25-api-removals-in-4.12=true
    - ack-4.12-kube-1.26-api-removals-in-4.13=true
    - ack-4.13-kube-1.27-api-removals-in-4.14=true
    - ack-4.15-kube-1.29-api-removals-in-4.16=true
    - ack-4.18-kube-1.32-api-removals-in-4.19=true
- files:
  - config.yaml=configmaps/cluster-monitoring-config.yaml
  name: cluster-monitoring-config
  namespace: openshift-monitoring

patches:
- path: kubeletconfigs/system-reserved-patch.yaml
- path: subscriptions/rhoai-operator-patch.yaml
- target:
    kind: SecretStore
  patch: |
    - op: replace
      path: /spec/provider/vault/auth/kubernetes/mountPath
      value: kubernetes/nerc-ocp-prod
- patch: |
    apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - name: mss-keycloak
        openID:
          clientID: ocp-prod
- patch: |
    apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - name: github
        github:
          clientID: 771ea98004d436c6e529
- target:
    kind: ExternalSecret
    name: oauths-clientsecret-nerc
  patch: |
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: nerc/nerc-ocp-prod/openshift-config/oauths-clientsecret-nerc
- target:
    kind: ExternalSecret
    name: aws-route53-credentials
  patch: |
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: nerc/nerc-ocp-prod/aws-route53-credentials
- target:
    kind: ExternalSecret
    name: github-client-secret
  patch: |
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: nerc/nerc-ocp-prod/openshift-config/github-client-secret
- target:
    kind: APIServer
    name: cluster
  patch: |
    - op: replace
      path: /spec/servingCerts/namedCertificates/0/names/0
      value: api.shift.nerc.mghpcc.org
- target:
    kind: PersistentVolumeClaim
    name: image-registry-storage
  patch: |
    - op: replace
      path: /spec/resources/requests/storage
      value: 750Gi
- target:
    kind: Subscription
    name: cluster-logging
  patch: |
    - op: replace
      path: /spec/channel
      value: stable-6.2
- target:
    kind: Subscription
    name: rhods-operator
  patch: |
    - op: replace
      path: /spec/channel
      value: stable-2.25
    - op: replace
      path: /spec/startingCSV
      value: rhods-operator.2.25.1
- target:
    kind: Subscription
    name: gpu-operator-certified
  patch: |
    - op: replace
      path: /spec/channel
      value: v25.10
- target:
    kind: Subscription
    name: serverless-operator
  patch: |
    - op: replace
      path: /spec/channel
      value: stable-1.36
