apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/acct-mgt
- ../../bundles/patch-operator
- ../../bundles/xdmod-reader
- ../../bundles/solr-helm-repo
- ../../bundles/ansible-automation-platform-operator
- ../../bundles/openshift-serverless-operator
- ../../bundles/amq-broker-rhel8-operator
- ../../bundles/crunchy-postgres-operator
- ../../bundles/amq-streams-operator
- feature/odf
- feature/custom-routes
- ../../base/core/namespaces/openshift-gitops
- externalsecrets
- apiserver/cluster.yaml
- secretstores
- issuers
- machineconfigs/configure-bond0
- nodenetworkconfigurationpolicies
- clusterversion.yaml
- certificates
- consolelinks

components:
  - ../../components/argocd-skip-dryrun

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - config.yaml=configmaps/cluster-monitoring-config.yaml
  name: cluster-monitoring-config
  namespace: openshift-monitoring

patches:
- path: ingresscontrollers/default_patch.yaml
- path: oauths/cluster_patch.yaml
- path: kubeletconfigs/system-reserved-patch.yaml
