apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/external-secrets-clustersecretstore
- clusterversion.yaml
- externalsecrets
- apiserver/cluster.yaml
- secretstores

patches:
- path: clustersecretstores/nerc-cluster-secrets_patch.yaml
- path: ingresscontrollers/default_patch.yaml
