apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/acct-mgt
- ../../bundles/metallb
- ingresscontrollers/external-apps-ingress-controller.yaml
- externalsecrets
- apiserver/cluster.yaml
- secretstores
- machineconfigs/configure-bond0
- nodenetworkconfigurationpolicies

patches:
- path: ingresscontrollers/default_patch.yaml
- path: oauths/cluster_patch.yaml

- target:
    group: "external-secrets.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"

- target:
    group: "operator.external-secrets.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"

- target:
    group: "nmstate.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"

- target:
    group: "redhatcop.redhat.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"
