apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: openshift-sriov-network-operator
resources:
- ../../base/core/namespaces/openshift-sriov-network-operator
- ../../base/operators.coreos.com/operatorgroups/openshift-sriov-network-operator
- ../../base/operators.coreos.com/subscriptions/openshift-sriov-network-operator
