apiVersion: v1
kind: Service
metadata:
  name: persistent-metrics-zookeeper
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app: persistent-metrics-zookeeper
    deployment: persistent-metrics-zookeeper
  sessionAffinity: None
  type: ClusterIP
