apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: nvidia-network-operator
resources:
- ../../base/core/namespaces/nvidia-network-operator
- ../../base/operators.coreos.com/operatorgroups/nvidia-network-operator
- ../../base/operators.coreos.com/subscriptions/nvidia-network-operator
