apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- projects

configMapGenerator:
- name: minio-config
  namespace: minio
  envs:
  - files/minio-config.env

patches:
  - path: externalsecrets/patch-minio-admin-credentials.yaml
  - path: persistentvolumeclaims/patch-pvc.yaml
