kind: ConfigMap
apiVersion: v1
metadata:
  name: observability-metrics-custom-allowlist
  namespace: open-cluster-management-observability
data:
  metrics_list.yaml: |
    names:
      - kube_persistentvolumeclaim_resource_requests_storage_bytes
      - kube_pod_spec_volumes_persistentvolumeclaims_info
      - kube_persistentvolumeclaim_info
      - kube_storageclass_info
      - kubelet_volume_stats_used_bytes
      - node_memory_MemTotal_bytes
      - node_network_receive_bytes_total
      - node_network_transmit_bytes_total
      - node_network_transmit_errs_total
      - node_network_transmit_packets_total
      - kube_pod_container_info
      - kube_pod_container_status_restarts_total
      - kube_pod_info
      - kube_pod_owner
      - kube_pod_resource_limits
      - kube_pod_resource_request
      - kube_pod_status_container_ready_time
      - kube_pod_status_initialized_time
      - kube_pod_status_ready_time
      - kube_pod_status_unschedulable
      - loki_distributor_bytes_received_total
    matches:
      - __name__=~"(ipmi_.*)"
      - __name__=~"(ceph_.*)"
      - __name__=~"(log_.*)"
      - __name__=~"(gpu_operator_.*)"
      - __name__=~"(DCGM_FI_.*)"
      - __name__=~"(argocd_.*)"
      - __name__=~"(kube_node_.*)"
