---
# Source: prometheus-snmp-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: prometheus-snmp-exporter-6.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-snmp-exporter
    app.kubernetes.io/name: prometheus-snmp-exporter
    app.kubernetes.io/version: "v0.27.0"
  name: prometheus-snmp-exporter
