apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - objectbucketclaims
  - operatorgroups
  - subscriptions
  - externalsecrets
  - configmaps
  - lokistacks
  - clusterroles
  - clusterrolebindings
commonLabels:
  app.kubernetes.io/name: loki
  app.kubernetes.io/component: lokistack
  app.kubernetes.io/part-of: cluster-logging
