apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerg.mghpcc.org/feature: external-ingress

resources:
- ingresscontrollers/external-apps.yaml
- externalsecrets/external-apps-ingress-certificate.yaml
