apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zookeeper
labels:
  - pairs:
      app: persistent-metrics-zookeeper
      deployment: persistent-metrics-zookeeper
    includeSelectors: true

resources:
  - deployments/
  - services/
