apiVersion: apps/v1
kind: Deployment
metadata:
  name: aitelemetry-site
spec:
  replicas: 3
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
  template:
    spec:
      volumes:
        - name: "ai-telemetry-developer"
          emptyDir: {}
      initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: git-cloner
          command:
            - sh
            - '-c'
          imagePullPolicy: Always
          volumeMounts:
            - name: "ai-telemetry-developer"
              mountPath: "/home/default/ai-telemetry-static/webawesome/templates/en-us/ai-telemetry-developer"
          terminationMessagePolicy: File
          envFrom:
            - secretRef:
                name: aitelemetry-worker
          image: docker.io/alpine/git
          args:
            - >-
              git clone https://computate.org:$GITHUB_DEVELOPERS_TOKEN@github.com/computate-org/ai-telemetry-developer.git /home/default/ai-telemetry-static/webawesome/templates/en-us/ai-telemetry-developer;
      containers:
        - name: aitelemetry
          image: 'quay.io/nerc-images/ai-telemetry:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 10210
              name: http
              protocol: TCP
            - containerPort: 10211
              name: cluster
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 'http'
            timeoutSeconds: 10
            failureThreshold: 10
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 'http'
            timeoutSeconds: 10
            failureThreshold: 10
          resources:
            requests:
              cpu: '500m'
              memory: '500Mi'
            limits:
              cpu: '1'
              memory: '2Gi'
          volumeMounts:
            - name: "ai-telemetry-developer"
              mountPath: "/home/default/ai-telemetry-static/webawesome/templates/en-us/ai-telemetry-developer"
          env:
            - name: ENABLE_ZOOKEEPER_CLUSTER
              value: 'true'
            - name: CLUSTER_HOST_NAME
              value: '0.0.0.0'
            - name: CLUSTER_PORT
              value: '10211'
            - name: CLUSTER_PUBLIC_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CLUSTER_PUBLIC_PORT
              value: '10211'
          envFrom:
            - secretRef:
                name: aitelemetry-zookeeper
            - secretRef:
                name: aitelemetry-solr
            - secretRef:
                name: aitelemetry-database
            - secretRef:
                name: aitelemetry-auth
            - secretRef:
                name: aitelemetry-site
