apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: default-ingress-certificate
  namespace: openshift-ingress
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: default-ingress-certificate
    template:
      type: kubernetes.io/tls
  dataFrom:
    - extract:
        key: nerc/nerc-ocp-prod/openshift-ingress/default-ingress-certificate
