apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- default-ingress-certificate.yaml
- default-api-certificate.yaml
- oauths-clientsecret-nerc.yaml
- github-client-secret.yaml
- github-group-sync-token.yaml
