apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: logging-grafana
  namespace: grafana
spec:
  deployment:
    envFrom:
      - configMapRef:
          name: grafana-config-overrides
  config:
    server:
      root_url: $GRAFANA_ROOT_URL
    auth.generic_oauth:
      enabled: true
      scopes: openid email groups profile
      email_attribute_path: name
      api_url: https://dex-dex.apps.nerc-ocp-infra.rc.fas.harvard.edu/userinfo
      auth_url: https://dex-dex.apps.nerc-ocp-infra.rc.fas.harvard.edu/auth
      token_url: https://dex-dex.apps.nerc-ocp-infra.rc.fas.harvard.edu/token
      role_attribute_path: >-
        contains(groups[*], 'cluster-admins') && 'Admin' ||
        contains(groups[*], 'nerc-org-admins')  && 'Admin' ||
        contains(groups[*], 'nerc-ops')   && 'Editor' ||
        'Deny'
      role_attribute_strict: true
