apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operatorgroups
  - subscriptions
  - configmaps
  - grafanas
  - grafanadatasources
  - routes
commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/component: grafana
  app.kubernetes.io/part-of: cluster-logging
