apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/node-feature-discovery
- ../../bundles/clusterissuer-http01
- ../../bundles/nerc-certificate-clusterissuers
- ../../bundles/external-secrets-clustersecretstore
- ../../bundles/grafana
- ../../bundles/crunchy-postgres-operator
- ../../bundles/keycloak
- ../../bundles/prom-keycloak-proxy
- ../../base/core/namespaces/openshift-gitops
- ../../base/core/namespaces/dex
- ../../base/rbac.authorization.k8s.io/clusterroles/allow-edit-rbac
- ../../base/operators.coreos.com/subscriptions/loki-operator
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/nerc-obs-admins-ops
- clusterversion.yaml
- externalsecrets
- logs-storage
- logsarchive-storage
- feature/odf
- certificates
- machineconfigs
- nodenetworkconfigurationpolicies

components:
  - ../../components/nerc-oauth-github

  # this must come last in order to apply
  # to all resources.
  - ../../components/argocd-skip-dryrun

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: admin-acks
  namespace: openshift-config
  behavior: merge
  literals:
    - ack-4.11-kube-1.25-api-removals-in-4.12=true
    - ack-4.12-kube-1.26-api-removals-in-4.13=true
- files:
  - config.yaml=configmaps/cluster-monitoring-config.yaml
  name: cluster-monitoring-config
  namespace: openshift-monitoring

patches:
- target:
    kind: SecretStore
  patch: |
    - op: replace
      path: /spec/provider/vault/auth/kubernetes/mountPath
      value: kubernetes/nerc-ocp-obs
- patch: |
    apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - name: github
        github:
          clientID: de5c05238a2bf843860f
          teams:
            - ocp-on-nerc/nerc-ops
            - ocp-on-nerc/nerc-logs-metrics
            - ocp-on-nerc/nerc-obs-admins
- target:
    kind: ExternalSecret
    name: aws-route53-credentials
  patch: |
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: nerc/nerc-ocp-obs/aws-route53-credentials
- target:
    kind: ExternalSecret
    name: github-client-secret
  patch: |
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: nerc/nerc-ocp-obs/openshift-config/github-client-secret
    - op: replace
      path: /spec/secretStoreRef
      value:
        kind: ClusterSecretStore
        name: nerc-cluster-secrets
- target:
    kind: APIServer
    name: cluster
  patch: |
    - op: replace
      path: /spec/servingCerts/namedCertificates/0/names/0
      value: api.obs.nerc.mghpcc.org
- target:
    kind: ClusterIssuer
    name: letsencrypt-.*-dns01
  patch: |
    - op: replace
      path: /spec/acme/solvers/0/selector/dnsZones
      value:
        - obs.nerc.mghpcc.org
- patch: |
    apiVersion: external-secrets.io/v1beta1
    kind: ClusterSecretStore
    metadata:
      name: nerc-cluster-secrets
    spec:
      provider:
        vault:
          auth:
            kubernetes:
              mountPath: kubernetes/nerc-ocp-obs
          server: https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/
