apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- machineconfigs/99-master-ssh.yaml
- machineconfigs/99-worker-ssh.yaml
- ../../base/operators.coreos.com/subscriptions/cert-manager
- ../../base/config.openshift.io/oauths/cluster
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/self-provisioners
- ../../bundles/openshift-operators-redhat
- ../../bundles/cluster-admin-rbac
- ../../bundles/external-secrets
- ../../bundles/nmstate
- ../../bundles/console
- ../../bundles/image-registry
- ../../bundles/logging
- ../../base/operator.openshift.io/ingresscontrollers/default
