apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/openapi
- ../../base/core/configmaps/admin-acks/
- ../../base/machineconfiguration.openshift.io/kubeletconfigs/system-reserved
- ../../base/config.openshift.io/oauths/cluster
- ../../base/rbac.authorization.k8s.io/clusterroles/node-labeler/
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/self-provisioners
- ../../bundles/cert-manager
- ../../bundles/openshift-operators-redhat
- ../../bundles/external-secrets
- ../../bundles/nmstate
- ../../bundles/console
- ../../bundles/image-registry
- ../../bundles/logging
- ../../bundles/group-sync-github
- ../../bundles/nerc-ops-rbac
- ../../base/operator.openshift.io/networks/cluster
- machineconfigs

components:
- ../../components/custom-certificates
