apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: weka-operator

helmCharts:
  - name: weka-operator
    namespace: weka-operator
    repo: oci://quay.io/weka.io/helm/weka-operator
    version: v1.7.0
    includeCRDs: true
    releaseName: weka-operator
    valuesFile: values.yaml
