apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: nerc-ops-rbac

resources:
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/nerc-ops
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-ops
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-ops-pod-exec
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-ops-portforward
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-ops-secrets-reader
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-ops-sudoer
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-ops-monitoring
