apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: external-apps-ingress-controller
  namespace: openshift-ingress-operator
spec:
  domain: apps.openshift.nerc.mghpcc.org
  defaultCertificate:
    name: external-apps-ingress-certificate
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: External
  nodePlacement:
    nodeSelector:
      matchLabels:
        zone: external
  namespaceSelector:
    matchLabels:
      type: external
