apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- apiserver/cluster.yaml
- ../common
- ../../bundles/patch-operator
- feature/odf
- machineconfigs/configure-bond0
- nodenetworkconfigurationpolicies/vlan-2175-nese.yaml
