apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- apiserver/cluster.yaml
- ../common
- ../../bundles/koku-metrics-operator
- ../../bundles/patch-operator
- externalsecrets/
- ../../bundles/rhods-operator
- ../../bundles/node-feature-discovery
- ../../bundles/nvidia-gpu-operator
- feature/odf
- machineconfigs/disable-net-ifnames
- machineconfigs/udev-rules
- machineconfigs/configure-bond0
- nodenetworkconfigurationpolicies/vlan-2175-nese.yaml
- secretstores
- clusterpolicies
- nodefeaturediscoveries

patches:
- path: oauths/cluster_patch.yaml
- target:
    kind: SecretStore
  patch: |
    - op: replace
      path: /spec/provider/vault/auth/kubernetes/mountPath
      value: kubernetes/nerc-ocp-test
