apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/node-feature-discovery
- ../../bundles/patch-operator
- ../../bundles/clusterissuer-http01
- ../../base/rbac.authorization.k8s.io/clusterroles/allow-edit-rbac
- ../../base/core/namespaces/openshift-gitops
- externalsecrets
- issuers
- feature/odf
- certificates
- nodenetworkconfigurationpolicies
- secretstores

components:
  - ../../components/nerc-oauth-github

  # this must come last in order to apply
  # to all resources.
  - ../../components/argocd-skip-dryrun

configMapGenerator:
- name: admin-acks
  namespace: openshift-config
  behavior: merge
  literals:
    - ack-4.15-kube-1.29-api-removals-in-4.16=true
- files:
  - config.yaml=configmaps/cluster-monitoring-config.yaml
  name: cluster-monitoring-config
  namespace: openshift-monitoring

generatorOptions:
  disableNameSuffixHash: true

patches:

- patch: |
    apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - name: github
        github:
          clientID: Ov23liIYFewHpMri8GO1
          teams:
            - ocp-on-nerc/nerc-ops
            - ocp-on-nerc/nerc-logs-metrics
            - ocp-on-nerc/nerc-rhods
- target:
    kind: ExternalSecret
    name: github-client-secret
  patch: |
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: nerc/nerc-ocp-test/openshift-config/github-client-secret

- target:
    kind: SecretStore
  patch: |
    - op: replace
      path: /spec/provider/vault/auth/kubernetes/mountPath
      value: kubernetes/nerc-ocp-test
- target:
    kind: ExternalSecret
    name: aws-route53-credentials
  patch: |
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: nerc/nerc-ocp-test/aws-route53-credentials
- target:
    kind: APIServer
    name: cluster
  patch: |
    - op: replace
      path: /spec/servingCerts/namedCertificates/0/names/0
      value: api.nerc-ocp-test.nerc.mghpcc.org
