apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-renderer-service-account-token
  namespace: grafana
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: grafana-renderer-service-account-token
  data:
  - secretKey: GRAFANA_SERVICE_ACCOUNT_TOKEN
    remoteRef:
      key: nerc/nerc-ocp-obs/grafana/renderer-token
      property: SERVICE_ACCOUNT_TOKEN
