apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- odhdashboardconfigs/odh-dashboard-config.yaml
- imagestreams/ucsls-f24-imagestream.yaml
- imagestreams/oauth-proxy.yaml
- acceleratorprofiles
- datascienceclusters
