apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/openshift-gitops
- ../../bundles/acm
- ../../bundles/acm/observability
- ../../bundles/hostpath-provisioner
- ../../bundles/vault
- ../../bundles/patch-operator
- ../../bundles/odf-external
- ../../bundles/external-secrets-clustersecretstore
- ../../base/core/namespaces/dex
- ../../base/core/namespaces/nerc-ocp-prod
- ../../base/operators.coreos.com/subscriptions/openshift-pipelines-operator
- ../../base/operators.coreos.com/subscriptions/loki-operator
- configmaps/admin-acks.yaml
- clusterversion.yaml
- machineconfigs/disable-net-ifnames.yaml
- machineconfigs/refresh-storage-interface.yaml
- machineconfigs/mellanox-udev-rules
- machineconfigs/configure-bond0
- nodenetworkconfigurationpolicies/vlan-2177-nese.yaml
- externalsecrets
- apiserver/cluster.yaml
- metrics-bucket-storage
- redhatcop.redhat.io/odf-node-patcher.yaml
- grafana-dashboards
- persistentvolumeclaims

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - config.yaml=configmaps/cluster-monitoring-config.yaml
  name: cluster-monitoring-config
  namespace: openshift-monitoring

patches:
- path: oauths/cluster_patch.yaml
- path: consoles.operator.openshift.io/cluster_patch.yaml
- path: storageclasses/ocs-external-storagecluster-ceph-rbd_patch.yaml
- path: clustersecretstores/nerc-cluster-secrets_patch.yaml
- path: ingresscontrollers/default_patch.yaml
- path: machineconfigs/hostpath-provisioner-selinux_patch.yaml
- path: externalsecrets/open-cluster-management-observability-multiclusterhub-operator-pull-secret_patch.yaml
- path: externalsecrets/open-cluster-management-observability-thanos-object-storage_patch.yaml
