apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/openshift-gitops
- ../../bundles/acm
- ../../bundles/acm/observability
- ../../bundles/vault
- ../../bundles/patch-operator
- ../../base/operator.openshift.io/networks/cluster
- ../../bundles/odf-external
- ../../bundles/external-secrets-clustersecretstore
- ../../base/core/namespaces/dex
- ../../base/core/namespaces/patch-operator
- ../../base/core/namespaces/grafana
- ../../base/core/namespaces/openshift-logging
- ../../base/core/namespaces/openshift-operators-redhat
- clusterversion.yaml
- machineconfigs/disable-net-ifnames.yaml
- machineconfigs/refresh-storage-interface.yaml
- machineconfigs/mellanox-udev-rules
- machineconfigs/configure-bond0
- nodenetworkconfigurationpolicies/vlan-2177-nese.yaml
- groupsyncs/github-ocp-on-nerc.yaml
- clusterrolebindings/nerc-ops-cluster-reader.yaml
- clusterrolebindings/nerc-ops-sudoers.yaml
- clusterrolebindings/nerc-ops-portforward.yaml
- externalsecrets
- apiserver/cluster.yaml
- metrics-bucket-storage

patches:
- path: oauths/cluster_patch.yaml
- path: consoles.operator.openshift.io/cluster_patch.yaml
- path: storageclasses/ocs-external-storagecluster-ceph-rbd_patch.yaml
- path: clustersecretstores/nerc-cluster-secrets_patch.yaml
- path: ingresscontrollers/default_patch.yaml

patchesStrategicMerge:
  - externalsecrets/open-cluster-management-observability-multiclusterhub-operator-pull-secret_patch.yaml
  - externalsecrets/open-cluster-management-observability-thanos-object-storage_patch.yaml
