apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"
resources:
- ../common
- ../../bundles/openshift-gitops
- ../../bundles/acm
- ../../bundles/odf
- clusterversion.yaml

patches:
  - path: oauths/cluster_patch.yaml
  - path: groups/cluster-admins_patch.yaml
