apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/openshift-gitops
- ../../bundles/acm
- ../../base/operator.openshift.io/networks/cluster
- ../../bundles/odf-external
- clusterversion.yaml
- machineconfigs/disable-net-ifnames.yaml
- machineconfigs/mellanox-udev-rules
- machineconfigs/configure-bond0
- nodenetworkconfigurationpolicies/vlan-2177-nese.yaml
- groupsyncs/github-ocp-on-nerc.yaml
- clusterrolebindings/nerc-ops-cluster-reader.yaml
- clusterrolebindings/nerc-ops-sudoers.yaml
- clusterrolebindings/nerc-ops-portforward.yaml

patches:
- path: oauths/cluster_patch.yaml
- path: consoles.operator.openshift.io/cluster_patch.yaml
